# Site settings
title: Sergio Bombolini
email: sbombolini@gmail.com
description: "Just Sergio Bombolini"
baseurl: ""
url: "sbombolini.github.io"
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
permalink: pretty
